print()
import time
print("Hi! How are you?")
time.sleep(2)
print()
name = input("May I please know your name : ")
time.sleep(2)
print()
print(f"Welcome, {name}. It is great to meet you!")
time.sleep(2)
print()
print("First of all, let's check what time is it now")
time.sleep(4)
import datetime
now = datetime.datetime.now()
print("so, let me see... mmm...")
time.sleep(2)
print()
print("now it is:")
time.sleep(1)
print()
print(now.strftime('%H:%M:%S'))
time.sleep(2)
print(now.strftime('on %A,'))
time.sleep(2)
print(now.strftime('%dth'))
time.sleep(2)
print(now.strftime('of the %B, %Y'))
time.sleep(4)
currenthour = int(now.strftime('%H'))
currentminute = int(now.strftime('%M'))
timedifference = ((23-currenthour)*60 + (60-currentminute))
print()
print("well, I ususally go into sleep mode at midnight sharp")
print()
time.sleep(4)
print("so guess what! we still got.....")
print()
time.sleep(2)
print(f"{timedifference} minutes to know each other!")
time.sleep(2)
print()
answer1 = input ("Isn't it wonderful? (yes, or any other answers) : ")
if answer1.lower().strip() == 'yes':
    print("Awesome! Great minds think alike!")
else:
    while True:
        answer2 = input("incorrect answer please try again, think harder : ")
        if answer2.lower().strip() == 'yes':
            break
    print()
    print("You did it!")
time.sleep(2)
print()
print()
answer3 = int(input("so now, how old are you? : "))
time.sleep(2)
print()
print(f"and please tell me {name}, have you had your birthday this year yet? : ")
print()
time.sleep(2)
answer4 = input("yes or no?")
time.sleep(2)
print()
if answer4 == "yes" :
    print()
    print ("alright, let me see")
    print()
    time.sleep(2)
    print ('so.....')
    print()
    time.sleep(2)
    print("80")
    time.sleep(2)
    print("minus your age,")
    time.sleep(2)
    print(f"which is {answer3}")
    time.sleep(2)
    print(f"That is 80 - {answer3} = {80-answer3}")
    time.sleep(2)
    print("plus 40,")
    time.sleep(2)
    print("equal to....")
    time.sleep(2)
    print(f"{80-answer3+40}")
    time.sleep(2)
    print(f"You were born in 19{80-answer3+40} !")
else:
    print ("alright, let me see")
    time.sleep(2)
    print ('so.....')
    time.sleep(2)
    print("79")
    time.sleep(2)
    print("minus your age,")
    time.sleep(2)
    print(f"which is {answer3}")
    time.sleep(2)
    print(f"That is 79 - {answer3} = {79-answer3}")
    time.sleep(2)
    print("plus 40,")
    time.sleep(2)
    print("equal to....")
    time.sleep(2)
    print()
    print(f"{79-answer3+40}")
    time.sleep(2)
    print()
    print(f"You were born in 19{79-answer3+40} !")
time.sleep(2)
print()
answer5 = input("Am I smart? I dare you would answer this question with a 'no' : ")
if answer5.lower().strip() == 'no':
    time.sleep(2)
    print()
    print("That's rude, my sleep mode just got actived by your answer..")
    time.sleep(3)
    print()
    for i in range(10):
        print ("goodbye,zzzzzzz")
else:
    time.sleep(2)
    print()
    print("Thanks! I might need a break now, talk later!")
